### ISSUE TITLE
Translation Needed - Chinese - GB_BLOKBOUNTY 

### ISSUE THREAD

**Issue by ArOhBeK** [GetBlok-io/Translations#1]
2 ERG Bounty per translation.

Looking for translations in the following languages:

Chinese
Portuguese
Spanish
Russian
German
Arabic

Translations must be true and will be verified (NO GOOGLE TRANSLATE). Please make sure to post a comment if you accept the bounty to avoid duplicative work.
Notify @ArOhBeK with any questions.

https://github.com/GetBlok-io/Translations/blob/main/GB_2022_BLOKBOUNTY.pptm

**Comment by linchiFTW** [comment]
I can handle the Chinese translation

**Comment by linchiFTW** [comment]
> I can handle the Chinese translation

Here you go! Kindly let me know if there are any issues.

[GB_2022_BLOKBOUNTY_ZH.pptx](https://github.com/GetBlok-io/Translations/files/7799140/GB_2022_BLOKBOUNTY_ZH.pptx)

**Comment by ArOhBeK** [comment]
> > I can handle the Chinese translation
> 
> Here you go! Kindly let me know if there are any issues.
> 
> [GB_2022_BLOKBOUNTY_ZH.pptx](https://github.com/GetBlok-io/Translations/files/7799140/GB_2022_BLOKBOUNTY_ZH.pptx)

Thank you. Great Job.   Kindly send me your ERG address.

**Comment by linchiFTW** [comment]
> > > I can handle the Chinese translation
> > 
> > 
> > Here you go! Kindly let me know if there are any issues.
> > [GB_2022_BLOKBOUNTY_ZH.pptx](https://github.com/GetBlok-io/Translations/files/7799140/GB_2022_BLOKBOUNTY_ZH.pptx)
> 
> Thank you. Great Job. Kindly send me your ERG address.

Sent via Discord DM. Thank you!
