### ISSUE TITLE
Translation Needed - Portuguese - GB_BLOKBOUNTY 

### ISSUE THREAD

**Issue by ArOhBeK** [GetBlok-io/Translations#2]
2 ERG Bounty per translation.

Looking for translations in the following languages:

Chinese
Portuguese
Spanish
Russian
German
Arabic

Translations must be true and will be verified (NO GOOGLE TRANSLATE). Please make sure to post a comment if you accept the bounty to avoid duplicative work.
Notify @ArOhBeK with any questions.

https://github.com/GetBlok-io/Translations/blob/main/GB_2022_BLOKBOUNTY.pptm

**Comment by d1stracao** [comment]
Hi @ArOhBeK,

I will write the Portuguese translation.

**Comment by Fir3line** [comment]
[GB_2022_BLOKBOUNTY.pptx](https://github.com/GetBlok-io/Translations/files/7799101/GB_2022_BLOKBOUNTY.pptx)
Done

**Comment by d1stracao** [comment]
> Hi @ArOhBeK,
> 
> I will write the Portuguese translation.

As mentioned before, here is the Portuguese translation. 
Please, if there are any issues let me know. Regards.


[GB_2022_BLOKBOUNTY_portuguese.pptx](https://github.com/GetBlok-io/Translations/files/7799346/GB_2022_BLOKBOUNTY_portuguese.pptx)

**Comment by ArOhBeK** [comment]
I will compensate both of you this time around.  However, please be sure to read details of Bounty.
