### ISSUE TITLE
Translation Needed - Spanish - GB_BLOKBOUNTY

### ISSUE THREAD

**Issue by ArOhBeK** [GetBlok-io/Translations#3]
2 ERG Bounty per translation.

Looking for translations in the following languages:

Chinese
Portuguese
Spanish
Russian
German
Arabic

Translations must be true and will be verified (NO GOOGLE TRANSLATE). Please make sure to post a comment if you accept the bounty to avoid duplicative work.
Notify @ArOhBeK with any questions.

https://github.com/GetBlok-io/Translations/blob/main/GB_2022_BLOKBOUNTY.pptm

**Comment by gharibehy** [comment]
work accepted

**Comment by gharibehy** [comment]
pull request created

**Comment by ArOhBeK** [comment]
Thanks great job https://explorer.ergoplatform.com/en/transactions/fe3e1288a934d26bfdd3d3eee1de6c265f0d11b96e4bbf7466c16e4f455e491c
