### ISSUE TITLE
Translation Needed - Russian - GB_BLOKBOUNTY

### ISSUE THREAD

**Issue by ArOhBeK** [GetBlok-io/Translations#4]
2 ERG Bounty per translation.

Looking for translations in the following languages:

Chinese
Portuguese
Spanish
Russian
German
Arabic

Translations must be true and will be verified (NO GOOGLE TRANSLATE). Please make sure to post a comment if you accept the bounty to avoid duplicative work.
Notify @ArOhBeK with any questions.

https://github.com/GetBlok-io/Translations/blob/main/GB_2022_BLOKBOUNTY.pptm

**Comment by truestorym** [comment]
Hey, here is my translation!
https://github.com/Mjasotrboob/Getblok/raw/main/GB_2022_BLOKBOUNTY.pptm

**Comment by ArOhBeK** [comment]
Thank you.  Please drop your ERG address for payment.

**Comment by truestorym** [comment]
Glad that I was of help!
Here is my wallet: 9hPKVwwGEUt9pVnYP53CYkDfANLETE1DdEE9mvN3WMHXoJwcyfr

**Comment by ArOhBeK** [comment]
Thanks again https://explorer.ergoplatform.com/en/transactions/13d0da8b1c08fb8c63611bb6a6262d62f67993db234a8808f3fd04aa18f8e989
