### ISSUE TITLE
Translation Needed - Arabic - GB_BLOKBOUNTY

### ISSUE THREAD

**Issue by ArOhBeK** [GetBlok-io/Translations#6]
2 ERG Bounty per translation.

Looking for translations in the following languages:

Chinese
Portuguese
Spanish
Russian
German
Arabic

Translations must be true and will be verified (NO GOOGLE TRANSLATE). Please make sure to post a comment if you accept the bounty to avoid duplicative work.
Notify @ArOhBeK with any questions.

https://github.com/GetBlok-io/Translations/blob/main/GB_2022_BLOKBOUNTY.pptm

**Comment by MaenB** [comment]
I will make the Arabic translation.

**Comment by MaenB** [comment]
Here is mine:
[GB_2022_BLOKBOUNTY_Arabic.pptx](https://github.com/GetBlok-io/Translations/files/7799841/GB_2022_BLOKBOUNTY_Arabic.pptx)

**Comment by MaenB** [comment]
also this is my address:
9gYsBHTuEQnKoAY6Jzbx3keyyJRgVosUBzoS9LzRUGFBq9wCCsU
thanks in advance :)

**Comment by ArOhBeK** [comment]
Received bad feedback on the proofreading.  I will compensate you, but we needed to correct this one.  Closing this issue as we corrected the file.

**Comment by MaenB** [comment]
Sorry for the inconvenience, the problem is just that arabic starts from right to left while English is the opposite I think this was the major problem that I had, 
Sorry again always glad to help 🙂
